### ISSUE TITLE
Please add comment feature, like hackmd comment

### ISSUE THREAD

**Issue by f-kawamura** [hedgedoc/hedgedoc#4351] opened 2023-06-30 03:16 UTC
### Is your feature request related to a problem? Please describe.

Hi.

I wanted to inquire if there are any plans to implement a comment functionality similar to HackMD Comment feature.

<img width="700" alt="image" src="https://github.com/hedgedoc/hedgedoc/assets/61042046/3bd0bc41-593e-4f2e-8847-4d6fc340b100">

### Describe the solution you'd like

The user should be able to comment any text in hedgedoc.

1. Users select the text they want to comment on.
2. They can write comments in response to the selected text.
3. Any other users can comment further on those comments.

### Describe alternatives you've considered

We are directly writing comments on the articles themselves. It can be quite challenging, as we are making our comments stand out.

**Comment by davidmehren** [comment] 2023-06-30 08:37
Duplicate of https://github.com/hedgedoc/hedgedoc/issues/657

**Closed by davidmehren** 2023-06-30 08:37 UTC
Labels: type: feature
