### ISSUE TITLE
Unable to delete with Android keyboard

### ISSUE THREAD

**Issue by DougInAMug** [hedgedoc/hedgedoc#651] opened 2021-01-03 23:49 UTC
**Description**
It is not possible to delete (backspace) characters using the stock Android (AOSP) keyboard, except characters which have been typed since opening the pad.

**To Reproduce**
1. Open hedgedoc pad on an Android device
2. Select `Android Keyboard (AOSP)`
3. Type something (it should still be deleteable at this point)
4. Refresh pad
5. *Cannot delete*

**Expected behavior**
I would expect that I can delete characters from any point in the pad history.

**Logs**
(no logs)

**Config**
(no config)

**Your Setup (please complete the following information):**
 - Host OS: Lineage OS 16.0 (Android 9)
 - Browser: Fennec F-Droid 84.1.2

**Additional context**
- *Workaround:* install `Keepass2Android` and select the Keepass2Android keyboard.
- I think I remember there being an issue for this already... but I couldn't find it? Lost on the recent migration perhaps? Anyway, I thought I would re-document since still current.

**Comment by ErikMichelson** [comment] 2021-01-04 00:00
See hedgedoc/react-client#437

Short summary: This is an upstream bug originating from our editor CodeMirror 5, and we aren't able to fix this now.

**Comment by davidmehren** [comment] 2021-01-04 20:01
Closing this as duplicate of https://github.com/hedgedoc/react-client/issues/437

**Closed by davidmehren** 2021-01-04 20:01 UTC
Labels: type: bug

**Comment by DougInAMug** [comment] 2021-01-07 10:55
Thanks @davidmehren - sorry I didn't manage to find the original (which I already commented on :facepalm: )
