### ISSUE TITLE
Microsoft Emoticon is crash appz

### ISSUE THREAD

**Issue by dexter74** [hedgedoc/hedgedoc#797] opened 2021-02-01 15:50 UTC
Bonjour,

Suite à l'utilisation d'un émoticône Windows, le conteneur crash en 404.

WIN+; > 🤦‍♂️

**Comment by mrdrogdrog** [comment] 2021-02-01 15:53
Sorry, but the main language or this project is english. Please reword your issue text.

**Comment by ErikMichelson** [comment] 2021-02-01 16:21
So as far as I can understand, you want to insert this emoji (🤦‍♂️) with the Microsoft Emoji-Picker and after inserting you get redirected to a 404 page?

I just excavated my Windows machine to test that behavior, but I can't reproduce it.

![image](https://user-images.githubusercontent.com/52606896/106485796-46845a00-64b1-11eb-8290-2fca9ff8fd11.png)


Some thoughts I still have in my mind:
 - Test whether the same thing happens if you use a clean browser-profile without any extensions/plugins.
 - Test whether you can reproduce the issue on our official demo instance at https://demo.hedgedoc.org.
 - If you host your own instance and use a MySQL/MariaDB database, check that UTF-8 support is enabled.

**Comment by davidmehren** [comment] 2021-03-11 20:48
Closing, as we can't reproduce the problem.

**Closed by davidmehren** 2021-03-11 20:48 UTC
Labels: type: bug
