### ISSUE TITLE
Documentation is unreadable

### ISSUE THREAD

**Issue by ulpaulpa** [hedgedoc/hedgedoc#747] opened 2021-01-21 12:18 UTC
**Which part of the project should be enhanced?**
The Documentation. https://github.com/hedgedoc/hedgedoc/blob/develop/docs/content/configuration.md 

**Is your enhancement request related to a problem? Please describe.**

I tried to fix the tables, but I gave up.

**Describe the solution you'd like**
I think that's pretty clear already

**Additional context**
I also realized, that the markdown syntax for tables is really bad for long text, because everything needs to be on one line. Maybe there would be a way for adding multiline tables in md (But then other people would need to adopt it too) or just display them nicer.

**Comment by ulpaulpa** [comment] 2021-01-21 12:24
Also the link to it [here](https://docs.hedgedoc.org/setup/manual-setup/) is wrong

**Comment by davidmehren** [comment] 2021-01-21 13:10
You can find a nicely rendered view of the docs here: https://docs.hedgedoc.org/configuration/

I'm not sure why the markdown got so broken, I'll look into fixing that.

> Also the link to it here is wrong

All links on this page seem to work for me. Which link do you mean?

**Comment by ulpaulpa** [comment] 2021-01-21 20:05
> Which link do you mean?
The 4th Point on Instructions

**Comment by mrdrogdrog** [comment] 2021-01-21 20:26
This issue is about the documentation on `develop`, which is known to be broken. I fixed the documentation on `master` in https://github.com/hedgedoc/hedgedoc/pull/750. This should fix the link on docs.hedgedoc.org.

**Comment by mrdrogdrog** [comment] 2021-01-21 20:39
Should be fixed on https://docs.hedgedoc.org now

**Comment by mrdrogdrog** [comment] 2021-01-22 16:07
Please close this issue if the problem is solved.

**Closed** 2021-01-22 16:39 UTC
Labels: type: enhancement
