### ISSUE TITLE
Internal Server Error when using oAuth2 login with roles claim

### ISSUE THREAD

**Issue by tionis** [hedgedoc/hedgedoc#2975] opened 2022-12-01 00:35 UTC
### Description

When authentication via oAuth2/OpenID is used, and the config specifies a value for the roles attribute as well as a role the user should have the server has an internal error, as outlined by the log message

### Steps to reproduce

1. Configure the server to login via oAuth2 using gitea as openid provider
2. Set the OAUTH2_ROLES_CLAIM to groups
3. Set the OAUTH2_ACCESS_ROLE to a gitea role
4. Try to login

### Expected behavior

Login should work for people having the specified role and show an error message for those who don't

### Logs

```shell
hedgedoc           | Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
hedgedoc           |     at new NodeError (node:internal/errors:387:5)
hedgedoc           |     at ServerResponse.setHeader (node:_http_outgoing:644:11)
hedgedoc           |     at ServerResponse.header (/hedgedoc/node_modules/express/lib/response.js:794:10)
hedgedoc           |     at ServerResponse.location (/hedgedoc/node_modules/express/lib/response.js:915:15)
hedgedoc           |     at ServerResponse.redirect (/hedgedoc/node_modules/express/lib/response.js:953:18)
hedgedoc           |     at complete (/hedgedoc/node_modules/passport/lib/middleware/authenticate.js:266:26)
hedgedoc           |     at /hedgedoc/node_modules/passport/lib/middleware/authenticate.js:278:15
hedgedoc           |     at pass (/hedgedoc/node_modules/passport/lib/authenticator.js:428:14)
hedgedoc           |     at Authenticator.transformAuthInfo (/hedgedoc/node_modules/passport/lib/authenticator.js:450:5)
hedgedoc           |     at /hedgedoc/node_modules/passport/lib/middleware/authenticate.js:275:22
hedgedoc           |     at /hedgedoc/node_modules/passport/lib/http/request.js:41:7
hedgedoc           |     at /hedgedoc/node_modules/passport/lib/sessionmanager.js:51:9
hedgedoc           |     at /hedgedoc/node_modules/connect-session-sequelize/lib/connect-session-sequelize.js:22:7
hedgedoc           |     at tryCatcher (/hedgedoc/node_modules/bluebird/js/release/util.js:16:23)
hedgedoc           |     at Promise._settlePromiseFromHandler (/hedgedoc/node_modules/bluebird/js/release/promise.js:547:31)
hedgedoc           |     at Promise._settlePromise (/hedgedoc/node_modules/bluebird/js/release/promise.js:604:18)
hedgedoc           |     at Promise._settlePromise0 (/hedgedoc/node_modules/bluebird/js/release/promise.js:649:10)
hedgedoc           |     at Promise._settlePromises (/hedgedoc/node_modules/bluebird/js/release/promise.js:729:18)
hedgedoc           |     at _drainQueueStep (/hedgedoc/node_modules/bluebird/js/release/async.js:93:12)
hedgedoc           |     at _drainQueue (/hedgedoc/node_modules/bluebird/js/release/async.js:86:9)
hedgedoc           |     at Async._drainQueues (/hedgedoc/node_modules/bluebird/js/release/async.js:102:5)
hedgedoc           |     at Immediate.Async.drainQueues [as _onImmediate] (/hedgedoc/node_modules/bluebird/js/release/async.js:15:14)
```

### Config
Configuration over env vars:
```shell
      - CMD_OAUTH2_USER_PROFILE_URL=https://tasadar.net/login/oauth/userinfo
      - CMD_OAUTH2_ROLES_CLAIM=groups
      - CMD_OAUTH2_ACCESS_ROLE="tasadar:user"
      - CMD_OAUTH2_PROVIDERNAME=Tasadar
      - CMD_OAUTH2_SCOPE="openid email profile"
      - CMD_OAUTH2_USER_PROFILE_USERNAME_ATTR=name
      - CMD_OAUTH2_USER_PROFILE_DISPLAY_NAME_ATTR=preferred_username
      - CMD_OAUTH2_USER_PROFILE_EMAIL_ATTR=email
      - CMD_OAUTH2_TOKEN_URL=https://tasadar.net/login/oauth/access_token
      - CMD_OAUTH2_AUTHORIZATION_URL=https://tasadar.net/login/oauth/authorize
      - CMD_OAUTH2_CLIENT_ID=some-id
      - CMD_OAUTH2_CLIENT_SECRET=some-secret
```

### Your Setup

- Host OS: Docker/Alpine
- HedgeDoc version: 1.9.6
- [Docker Image used](https://quay.io/repository/hedgedoc/hedgedoc/manifest/sha256:2bda27dabdc9976a9ef550f28ecf4b6976b505c85f41395c5dfa0f906a89de0d)

**Comment by davidmehren** [comment] 2022-12-18 18:54
Duplicate of https://github.com/hedgedoc/hedgedoc/issues/795

**Closed by davidmehren** 2022-12-18 18:54 UTC
Labels: type: bug
