### ISSUE TITLE
Switching between light/dark mode does not work

### ISSUE THREAD

**Issue by lkiesow** [hedgedoc/hedgedoc#3334] opened 2023-02-14 11:55 UTC
### Description

Switching between light and dark modes in HedgeDoc des not always work

### Steps to reproduce

1. Open a document
2. Switch to dark mode
3. Reload
    - The problem seems to appear if you open the doc in dark mode
5. Switch to light mode
    - This will work
7. Switch to dark mode
    - Switching modes no longer works

### Expected behaviour

You should be able to continuously switch between light and dark mode

### Logs

```shell
No obvious errors in server logs or browser console
```

### Your Setup

- Host OS: Docker
- HedgeDoc version: quay.io/hedgedoc/hedgedoc:1.9.6
- Browser: Firefox 107

**Comment by davidmehren** [comment] 2023-02-14 13:39
Can reproduce on demo.hedgedoc.org

**Comment by mrdrogdrog** [comment] 2023-02-14 14:08
Not a critical bug therefore no fix intended for 1.x.

**Comment by ErikMichelson** [comment] 2023-02-19 20:50
This has been fixed anyway and will be released with the next 1.x release.

**Closed by ErikMichelson** 2023-02-19 20:50 UTC
Labels: type: bug, status: confirmed
