### ISSUE TITLE
Possibility to add Subpads

### ISSUE THREAD

**Issue by fionera** [hedgedoc/hedgedoc#2639] opened 2022-09-04 21:44 UTC
### Is your feature request related to a problem? Please describe.

When I have a big Pad with custom URLs its always a struggle to organize it since large pads are not easy to overview

### Describe the solution you'd like

A way to cross-link pads or create child pads and then switch between them via a overlay	

### Describe alternatives you've considered

Having one Pad that has a list of other pad links

**Comment by DerMolly** [comment] 2022-09-04 21:55
Hey @fionera,

thanks for your suggestion, but this look like a duplicate of https://github.com/hedgedoc/hedgedoc/issues/1001.

If not feel free, to reopen this issue and explain more.

**Closed by DerMolly** 2022-09-04 21:55 UTC
Labels: type: feature
