### ISSUE TITLE
Double-click to jump to source

### ISSUE THREAD

**Issue by quazlyy** [hedgedoc/hedgedoc#5571] opened 2024-04-25 08:18 UTC
### Is your feature request related to a problem? Please describe.

From using other similar editors (Overleaf, VS Code, etc.) I'm used to being able to double-click a line in the rendered view to jump to the corresponding line in the source Markdown text. This is currently not supported in HedgeDoc

### Describe the solution you'd like

It would be great if you could double-click on a text in the rendered visualization panel to jump to the corresponding line in the Markdown source

### Describe alternatives you've considered

The alternative is to select the line manually

**Comment by ErikMichelson** [comment] 2024-04-25 14:42
Hey @quazlyy,

thanks for your time suggesting this feature. There is already another issue for the same topic, therefore I'm going to close this one.

Duplicate of #2917

**Closed by ErikMichelson** 2024-04-25 14:42 UTC
Labels: type: feature
