### ISSUE TITLE
Can't select parts of code via touchscreen

### ISSUE THREAD

**Issue by kabajau** [hedgedoc/hedgedoc#3197] opened 2023-01-21 16:06 UTC
### Description

I am unable to select a part of code via touchscreen when using hedgedoc on an android device. It's only possible to "select all".

### Steps to reproduce

1. Open a hedgedoc pad in Chrome for Android.
2. Switch to "Edit" mode.
3. Try to select by pressing and holding down on a part of code.
4. Nothing is selected. Instead a context menu shows up, where the only option is to "select all".

### Expected behaviour

The word that is being pressed on is selected and the selection can be expanded or reduced with 2 carets.

### Your Setup

- HedgeDoc version: 1.9.6

**Comment by davidmehren** [comment] 2023-01-21 21:06
Duplicate of #2081

**Closed by davidmehren** 2023-01-21 21:06 UTC
Labels: type: bug
