### ISSUE TITLE
Login with Screenreader in Firefox not possible

### ISSUE THREAD

**Issue by WestphalDenn** [hedgedoc/hedgedoc#1155] opened 2021-04-19 09:33 UTC
**Description**

I as a blind user want to login using Firefox and the Screenreader NVDA. Both in the current stable version. 

**To Reproduce**

* Using Firefox go to your HedgeDoc start page. 
* Using NVDA press the letter "b" to go to the Button "Sign in"
* Press the ENTER-Key to activate the button. 
* With keyboard only try to find the textfield to enter your credentials. 

**Expected behavior**
After activating the "Sign in" button focus should jump to the textfield to login. 

**Additional context**
This beaviour is seen only in Firefox. In Chrome on Windows as well as Safari on the Mac I am able to log in just fine.

**Comment by DerMolly** [comment] 2021-04-19 10:47
We just tried to reproduce this and it worked for us. But we tested this on Linux, I guess you tried it on Windows and macos? Is this assumption correct?

**Comment by WestphalDenn** [comment] 2021-04-20 11:30
Yes that is correct. I tested that with NVDA on Windows 10. 

Using Firefox on the Mac gave me the same result. To be clear. visually the log in gialog is on the screen in both instances. The difference is that the screenreader doesn't see it using the Firefox browser. Since I am seeing the same behaviour on Windows and on Mac where practically the only thing that stays the same is the browser it might be some issue with Screenreaders and Firefox.

**Comment by mrdrogdrog** [comment] 2021-04-20 12:43
Hm. That's odd. Especially because the log in screen focus the user name text box immediately. I have some ideas for (hopefully easy) fixes that MIGHT solve this issue. Would you like to help us and test them?

**Comment by WestphalDenn** [comment] 2021-04-22 07:54
Sure I'd love to help.

**Comment by mrdrogdrog** [comment] 2022-04-03 19:42
Duplicate of https://github.com/hedgedoc/hedgedoc/issues/2126

**Closed by mrdrogdrog** 2022-04-03 19:42 UTC
Labels: type: bug
