### ISSUE TITLE
type a short title of your bug report here

### ISSUE THREAD

**Issue by maxgrass** [hedgedoc/hedgedoc#2264] opened 2022-04-13 11:47 UTC
### Description

Fix selection of text in edit mode on iOS/Safari.

### Steps to reproduce

1. On an iPhone, open a doc in edit mode, type some words.
2. Try to use iPhone text selection (word double/triple click or hold on cursor to show the text-menu with select-all, paste etc.).

### Expected behaviour

1. Native iOS text selection and 2. iOS built-in menu for text manipulation (cut/copy/paste/select all)
must work, because it's the core of notes -> text editing.

### Your Setup

- Host OS: Ubuntu 20.04 / docker basic try-out version 
- NodeJS version: docker
- HedgeDoc version: 193

**Comment by davidmehren** [comment] 2022-04-13 11:52
Duplicate of https://github.com/hedgedoc/hedgedoc/issues/2081

**Closed by davidmehren** 2022-04-13 11:52 UTC
Labels: type: bug
