### ISSUE TITLE
The HTML Export Option is not working on the website

### ISSUE THREAD

**Issue by LabinatorSolutions** [hedgedoc/hedgedoc#1484] opened 2021-07-29 02:20 UTC
**Description**
When clicking the "HTML" option from the menu under the "Export" category, nothing happens. It used to work in the past but not anymore. In other words, we can not export the files to HTML anymore.

**To Reproduce**
1. Go to https://demo.hedgedoc.org/
2. Click on "new guest note".
3. Write any text.
4. Click on the "menu" button.
5. Click on "HTML" under the "Download" category.
6. Nothing happens!

**Expected behavior**
Ability to export the file to HTML.

**Comment by ErikMichelson** [comment] 2021-07-29 10:13
I can confirm this.
Seems to be that we use some kind of `eval` there which is now forbidden by CSP.

```
code-gen.js:169 Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' vimeo.com https://gist.github.com www.slideshare.net 'nonce-c313ee42-f206-4f7c-9b8b-5ba0a280fb47' 'sha256-81acLZNZISnyGYZrSuoYhpzwDTTxi7vC1YM4uNxqWaM='".
```

**Comment by ErikMichelson** [comment] 2021-07-29 20:09
I tested this with local setups and a few other instances. None of them had this problem, it seems to be related just to the demo.hedgedoc.org instance.

**Comment by mrdrogdrog** [comment] 2021-07-29 20:17
The version that is deployed on the demo instance doesn't include this commit https://github.com/hedgedoc/hedgedoc/commit/938afbddc33c538300a68ee74cbbe8c6db6f858b. That could be the reason because it changes the way the export works. Seems like handlebars needs `unsafe-eval`. So it should work again if we update the demo instance.

/cc @SISheogorath

**Comment by ErikMichelson** [comment] 2021-07-30 15:45
Should be fixed with the update on the demo instance.

**Closed** 2021-07-30 15:45 UTC
Labels: priority: high, scope: demo instance, status: confirmed, type: bug
