### ISSUE TITLE
Don't scroll when someone else adds text above your view

### ISSUE THREAD

**Issue by TrAyZeN** [hedgedoc/hedgedoc#1903] opened 2021-12-15 22:48 UTC
### Which part of the project should be enhanced?

Editing window

### Is your enhancement request related to a problem? Please describe.

When editing a document in collaboration when someone else inserts or removes lines above your view, the view is not scrolled. This means that the text your are viewing appears to be shifted below if the person added lines. What I mean by view is the view into the document in editing mode.

### Describe the solution you'd like

Make the view stick with the currently viewed text the default behavior.

### Describe alternatives you've considered

If not making the view stick is an expected behavior then add a button to toggle an option to make the view stick.

**Comment by davidmehren** [comment] 2021-12-16 08:58
Duplicate of https://github.com/hedgedoc/react-client/issues/465

**Closed by davidmehren** 2021-12-16 08:58 UTC
Labels: type: enhancement
