### ISSUE TITLE
Feature Request: Add the ability to follow someone's cursor

### ISSUE THREAD

**Issue by ZZYSonny** [hedgedoc/hedgedoc#606] opened 2020-11-30 05:30 UTC
**Is your feature request related to a problem? Please describe.**

Currently if someone is writing at the end of document. Other users have to constantly scroll down to read latest text. 

**Describe the solution you'd like**

Add an option to follow someone's cursor. 

**Describe alternatives you've considered**

Or could go the other side. Someone requests everyone to follow its cursor. 

**Additional context**

**Comment by DerMolly** [comment] 2020-11-30 15:17
I think this is already covered by https://github.com/hedgedoc/react-client/issues/281 and can be closed…

**Comment by davidmehren** [comment] 2020-12-01 20:16
Yep, looks like we already track that feature in the new frontend.

Duplicate of https://github.com/hedgedoc/react-client/issues/281

**Closed by davidmehren** 2020-12-01 20:16 UTC
Labels: scope: frontend, type: feature
