### ISSUE TITLE
Template documents

### ISSUE THREAD

**Issue by trini** [hedgedoc/hedgedoc#1108] opened 2021-04-06 19:21 UTC
**Is your feature request related to a problem? Please describe.**

We use Hedgedoc for note taking on calls and project kicks-offs.  For every one of these I start a blank document, put in a tag for kick-off (so that all kick-offs can be found for later reference) and paste in a skeleton set of bullet points of questions we need to agree on answers to.

**Describe the solution you'd like**

I would like to see a "duplicate" or "save as" or similar option for an existing note.  That way I could make a template note, click a button and then start editing it for the new project.

**Describe alternatives you've considered**

A functional-enough work-around is that I simply have a note today that is the template and I copy/paste that to a new note for each project.

**Additional context**

**Comment by davidmehren** [comment] 2021-04-06 20:03
Duplicate of https://github.com/hedgedoc/react-client/issues/90

**Closed by davidmehren** 2021-04-06 20:03 UTC
Labels: type: feature
