### ISSUE TITLE
Links to Anchors in a Document Don’t Include the Document ID

### ISSUE THREAD

**Issue by andreasdomanowski** [hedgedoc/hedgedoc#3905] opened 2023-04-27 07:38 UTC
### Description

HedgeDoc creates links to anchors for headings. These do not include the document id but point to the instance's main path appended with the anchor.

### Steps to reproduce

1. Create a document with a heading
2. Inspect the link in the "View"-view left to the heading

### Expected behaviour

The link should contain the document ID (e.g. my.domain/$DOCUMENT_ID#myheading).

### Your Setup

- Host OS: Debian 11
- Containerized HedgeDoc (_quay.io/hedgedoc/hedgedoc:1.9.7_)

**Comment by ErikMichelson** [comment] 2023-06-04 00:57
Duplicate of #2344

**Closed by ErikMichelson** 2023-06-04 00:57 UTC
Labels: type: bug
