### ISSUE TITLE
Hedgedoc 2 : Title are not showned correctly in history mode

### ISSUE THREAD

**Issue by GGH-WeyboZetO** [hedgedoc/hedgedoc#3783] opened 2023-04-12 18:06 UTC
### Description

Title are not showned correctly in history mode

### Steps to reproduce

Create a new note, and write a title.
![titlebug](https://user-images.githubusercontent.com/93222701/231543014-ce934d72-7ca0-463d-a856-c47f9da5e84f.png)

Click Hedgedoc logo, then click history
![titlebug2](https://user-images.githubusercontent.com/93222701/231543211-dc84e2b3-68fb-4ad5-a67c-0df5156356a1.png)

### Expected behaviour

It should show the title correctly.

### Your Setup

- Host OS: [e.g. Ubuntu 20.04]
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal

- NodeJS version: v16.19.1
- HedgeDoc version: 2.0.0-dev

### Additional context

If that's truly a bug I would like to work on it since it looks like an easy fix, could you tell me exactly where in the code are the methods assigning title value from work to history.

If that's not a bug, my bad you can close that issue.

**Comment by ErikMichelson** [comment] 2023-04-12 18:53
Hi, this is not a bug but not implemented yet. However we're working on it (see #3757 or #3771) for example. Therefore I'm going to close this issue.

**Closed by ErikMichelson** 2023-04-12 18:53 UTC
Labels: type: bug
