### ISSUE TITLE
Unintended note creation in FreeURL mode

### ISSUE THREAD

**Issue by nidico** [hedgedoc/hedgedoc#754] opened 2021-01-22 15:47 UTC
If FreeURL mode is enabled, a single `GET` request on a non-existing note immediately creates that note.

This may lead to many accidentally created notes. In addition, there are many bots which try out known paths (`/wp-admin` etc) in order to automate attack attempts or to just map the web. We just discovered quite a few notes which have been created by such bots on a relatively unknown HedgeDoc instance.

Possible solutions / mitigations:

- Create a modal dialog when opening a formally unknown note and require a POST on a given form (e.g. a button labeled "Yes, please create the note/pad"). This is what etherpad "classic" (not etherpad-lite) is doing. This would mitigate accidental creations as well as stupid bots which just randomly try out URLs and do not actively try to "DDOS" HedgeDoc.

- Allow to restrict FreeURL mode to authenticated users. This would avoid the "bot spam". Of course this is a limitation for unauthenticated users, but it's still better than disabling FreeURL mode entirely.

As the latter is easy to implement and backward compatible and at least solves the problem for us, I'm going to submit a PR for that option.

I'd propose to allow that simple addition in HedgeDoc 1.7.x (as it solves real problems *now*) and to do something like a modal dialog in HedgeDoc 2.x.

**Comment by davidmehren** [comment] 2021-01-22 16:24
> If FreeURL mode is enabled, a single GET request on a non-existing note immediately creates that note.

I'd call that "works as intended" :D
So yes, this behavior creates more rows in the database, but that doesn't look like a big problem to me.

Regarding your PR:
A new config option is a new feature, which calls for a new minor release, which we do not plan to do for 1.x.

**Comment by nidico** [comment] 2021-01-22 16:40
> I'd call that "works as intended" :D
> So yes, this behavior creates more rows in the database, but that doesn't look like a big problem to me.

I understand there may be diverging views on the criticality of the issue. We considered the issue *that bad* that we decided to disable FreeURL although we really much like it. Hence the PR, which we'll most likely deploy, even if the PR wouldn't be merged upstream (although this would create additional work)...

>  A new config option is a new feature, which calls for a new minor release, which we do not plan to do for 1.x.

I had hoped this could slip through in a 1.7.x release as it's non-breaking and partially fixes a bug (if you call it that way).

**Comment by davidmehren** [comment] 2021-01-22 16:45
> We considered the issue that bad that we decided to disable FreeURL although we really much like it.

Could you elaborate on why you think this is so bad?

You could also join us on Matrix in [#hedgedoc:matrix.org](https://matrix.to/#/#hedgedoc:matrix.org?via=matrix.org&via=kif.rocks&via=hackerspaces.be) to discuss this further if you prefer.

**Comment by nidico** [comment] 2021-01-23 13:27
> Could you elaborate on why you think this is so bad?

Sure, as written in the matrix channel (but I also want to add it here for the general public): Technically this indeed doesn't seem *that* bad, as it's just a couple of (almost empty) entries in the `Notes` table which are added.

Nevertheless it feels wrong to fill up the database with avoidable spam. From a "restrictive administrator" perspeictive, it makes it hard to keep track of the usage of the installation if the list of notes is full of spam.

**Comment by ErikMichelson** [comment] 2021-02-21 12:17
The linked PR has been merged. Can this issue be closed?

**Closed** 2021-02-21 12:20 UTC
Labels: priority: medium, type: bug, type: enhancement
