### ISSUE TITLE
Horizontal (top/bottom) editing mode

### ISSUE THREAD

**Issue by depau** [hedgedoc/hedgedoc#4608] opened 2023-08-09 17:22 UTC
### Describe the solution you'd like

When taking notes I often use HedgeDoc on my vertical display. It would be very useful to have the editor on top and the preview on the bottom (or the opposite) instead of the left/right layout.

### Describe alternatives you've considered

I usually open two browser windows and tile them, one in view mode and the other in edit mode, but that doesn't sync the vertical scrolling position. Perhaps if scroll syncing over multiple windows would be implemented that would solve my use-case.

**Comment by mrdrogdrog** [comment] 2023-08-09 17:48
Duplicate of #2883

**Closed** 2023-08-09 17:48 UTC
Labels: type: feature
