### ISSUE TITLE
running ./bin/setup failed: meta-marked: The remote archive doesn't match the expected checksum

### ISSUE THREAD

**Issue by gaenseklein** [hedgedoc/hedgedoc#5226] opened 2023-10-30 16:01 UTC
### Description

i tried to install hedgedoc via .tar.gz and git-clone method (v.1.9.9) and running ./bin/setup fails. 
complete output: 
```
Copying config files...
Installing packages...
➤ YN0000: ┌ Resolution step
➤ YN0060: │ HedgeDoc@workspace:. provides sequelize (p91ea1) with version 5.22.5, which doesn't satisfy what connect-session-sequelize requests
➤ YN0002: │ HedgeDoc@workspace:. doesn't provide webpack (p83411), requested by clean-webpack-plugin
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0013: │ xtraverse@npm:0.1.0 can't be found in the cache and will be fetched
➤ YN0013: │ yallist@npm:4.0.0 can't be found in the cache and will be fetched f
➤ YN0013: │ yeast@npm:0.1.2 can't be found in the cache and will be fetched fro
➤ YN0013: │ zip-stream@npm:4.1.0 can't be found in the cache and will be fetche
➤ YN0013: │ meta-marked@https://github.com/hedgedoc/meta-marked.git#commit=0cb5
➤ YN0018: │ meta-marked@https://github.com/hedgedoc/meta-marked.git#commit=0cb5065253ab0f9851baec34dc9edbb40eabf3d0: The remote archive doesn't match the expected checksum
➤ YN0000: └ Completed in 11s 299ms
➤ YN0000: Failed with errors in 11s 429ms

```

### Steps to reproduce

follow installation-steps :
2. Download the [latest release](https://hedgedoc.org/latest-release/) and extract it.
Alternatively, you can use Git to clone the repository and checkout a release, e.g. with git clone -b 1.9.9 https://github.com/hedgedoc/hedgedoc.git.
3. Enter the directory and execute bin/setup, which will install the dependencies and create example configs.

### Expected behaviour

installation should finish without problems

### Your Setup

- Host OS: Debian 11.8
- NodeJS version: v16.20.2
- HedgeDoc version: 1.9.9
- Yarn version: 3.6.1

**Comment by ErikMichelson** [comment] 2024-01-04 14:27
We'll need to further investigate this. I just tried this again in a clean environment and cannot reproduce the issue.

Test setup:
* Linux x64
* Docker with node 20 (`docker run --rm -it node:20 bash`)
* HedgeDoc 1.9.9 tar.gz bundle from the website (https://hedgedoc.org/releases/1.9.9/)
* Downloading the bundle and running `bin/setup` from inside the container

**Comment by mgauthier2024** [comment] 2024-01-22 14:58
I am also getting "archive doesn't match the expected checksum" messages, but with different packages :


```
    ➤ YN0018: │ lz-string@https://github.com/hackmdio/lz-string.git#commit=efd1f64676264d6d8871b01f4f375fc6ef4f9022: The remote archive doesn't match the expected checksum
    ➤ YN0018: │ Idle.Js@https://github.com/shawnmclean/Idle.js.git#commit=2b57cc6e49d177b7ddce0cca00ef5cbe07453541: The remote archive doesn't match the expected checksum
```

Deployment setup:

- Debian 12 (VM)
- Node.js 18.x (from `deb.nodesource.com`)
- Yarn installed from corepack (`corepack enable` after `npm i -g corepack`)
- HedgeDoc 1.9.9 acquired through `git clone`
- `bin/setup` from shell

**Comment by davidmehren** [comment] 2024-08-31 15:29
Should be fixed by https://github.com/hedgedoc/hedgedoc/pull/5760

**Closed by davidmehren** 2024-08-31 15:29 UTC
Labels: type: bug
