### ISSUE TITLE
postgres relation "public.sequelizemeta_pkey" does not exist

### ISSUE THREAD

**Issue by smithbk** [hedgedoc/hedgedoc#2246] opened 2022-04-07 00:34 UTC
### Description

I configured hedgedoc to connect to a newly provisoned AWS postgres instance, but it fails to start with a "Database migration failed" error.

### Steps to reproduce

1. Provisioned a new instance of AWS postgres
2. Configured the following environment variables
    ```
    CMD_DB_DIALECT=postgresql
    CMD_DB_PORT
    CMD_DB_USERNAME
    CMD_DB_DATABASE
    CMD_DB_PASSWORD
    CMD_DB_HOST
    ```
3. npm run start

### Expected behaviour

Start successfully and initialize the DB

### Logs

```shell
$ npm run start

> HedgeDoc@1.9.2 start /opt/app-root/src/hedgedoc
> node app.js

2022-04-06T23:49:26.576Z debug: 	dmp worker process started
2022-04-06T23:49:26.945Z error: 	relation "public.sequelizemeta_pkey" does not exist
2022-04-06T23:49:26.945Z error: 	Database migration failed.
This can be the result of upgrading from quite old versions and requires manual database intervention.
See https://docs.hedgedoc.org/guides/migration-troubleshooting/ for help.
Exiting…
```

### Config

```shell
CMD_DB_DIALECT=postgresql
    CMD_DB_HOST=
    CMD_DB_PORT=5432
    CMD_DB_DATABASE=hedgedocdb
    CMD_DB_USERNAME=
    CMD_DB_PASSWORD=
```

### Your Setup

- Host OS: RHEL 8.5
- NodeJS version: v14.17.5
- HedgeDoc version: 1.9.2

### Additional context

The following shows the existing postgres relations

hedgedocdb=> \dt
                 List of relations
 Schema |          Name          | Type  |  Owner   
--------+------------------------+-------+----------
 public | custom_time_partitions | table | rdsadmin
 public | part_config            | table | rdsadmin
 public | part_config_sub        | table | rdsadmin
(3 rows)

**Comment by davidmehren** [comment] 2022-05-22 16:09
I *suspect* this has something to do with AWS's Postgres, as nobody else using Postgres complained about broken migrations.

Unfortunately, I can't try to reproduce this, as I don't work with AWS, sorry.

**Comment by DerMolly** [comment] 2022-10-09 20:40
I don't think we can fix this issue with the current information and available databases. As this seems to be AWS specific bug, we would need further explanations to fix this. In the mean time I'll close this issue, because we don't have any way to go from here…

**Closed by DerMolly** 2022-10-09 20:40 UTC
Labels: type: bug
