### ISSUE TITLE
CodiMD display line break even when it's not supposed to

### ISSUE THREAD

**Issue by TheFrenchGhosty** [hedgedoc/hedgedoc#580] opened 2020-11-17 15:26 UTC
**Description**

When writing markdown, doing a line break isn't supposed to display line break in a proper markdown visualizer.

To do a line break in markdown you either have to do 2 line break in the raw text, or you have to add two spaces at the end of the previous line and add a line break.

Problems: 

- CodiMD display 1 line break in the raw text,  as a line break in markdown, instead of no line break.

- CodiMD display 2 line break in the raw text, as 2 line breaks in markdown, instead of one.

Why is it an issue: if I want to write in CodiMD and then put the content in any other software, every single line break / double line break in CodiMD will not be displayed in the same way. In my opinion CodiMD should follow the "standard", and not do things differently. 

**To Reproduce**

Write that in CodiMD, and compare the visualization to any other markdown visualizer (Okular, Github...):

```
CodiMD linebreak bug:

---

This is a sentence where line break happen
even when it's not supposed to.

---

This is a sentence where line break happen

even when it's not supposed to.

---

This is a sentence where line break happen  
correctly.
```

**Expected behavior**

The markdown visualizer handle line breaks in the same way every other software does.

**Additional context**

CodiMD:

![codimd](https://user-images.githubusercontent.com/47571719/99409270-17fed600-28e9-11eb-8b77-26ee47ba0080.png)

Okular (as you can see Okular display 2 line break in the raw text differently than 2 space and line break, from what I know, it's a feature).

![okular](https://user-images.githubusercontent.com/47571719/99409289-1e8d4d80-28e9-11eb-8a28-882880505487.png)

**Comment by DerMolly** [comment] 2020-11-17 17:34
It's possible to change this behavior see https://demo.hedgedoc.org/yaml-metadata#breaks.

And you can change the default.md file in your Server to always activate this option.

Changing the default behavior is a bit problematic as many people expect this behavior from HedgeDoc.

**Comment by davidmehren** [comment] 2020-11-17 18:24
This is also a duplicate of #59, where the workaround was already discussed.
Unfortunately, this is something we can't just change globally, as it would change the rendering of already existing notes.

**Closed by davidmehren** 2020-11-17 18:24 UTC
Labels: bug

**Comment by TheFrenchGhosty** [comment] 2020-12-04 16:24
@davidmehren 

(sorry it took me a while to answer)

> Unfortunately, this is something we can't just change globally, as it would change the rendering of already existing notes.

Why not just set this option on a per-file basis? Add this as a feature, and set every existing note to use the "current" handling.

**Comment by SISheogorath** [comment] 2020-12-05 13:39
@TheFrenchGhosty It is already a per note option. One should mention, that HedgeDoc doesn't store note content in form of files.

Besides that, you can change the global default by adjusting the `default.md` file in your installation and add the yaml-metadata there. This won't break any existing note and doesn't require any code changes.
